# Generated by Django 4.0.3 on 2022-04-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileManagemenent',
            new_name='UserProfileManagemennt',
        ),
    ]
