# Generated by Django 4.0.3 on 2022-04-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_userprofilemanagemenent_userprofilemanagemennt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileManagemennt',
            new_name='UserProfileManagement',
        ),
    ]
